services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:20
    volumes:
      - "./app:/var/www"
    ports:
      - "3000:3000"
    # links:
    #   - db
  # db:
  #   image: mongo
  #   ports:
  #     - "27017:27017"